import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for push events
self.addEventListener('push', (event) => {
  let data = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: 'Smart Daily Planner', body: event.data.text() };
    }
  }

  const options = {
    body: data.body || data.message || 'You have an upcoming event scheduled!',
    icon: '/pwa-192x192.png',
    badge: '/favicon.svg',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/notifications',
      notificationId: data.notificationId
    }
  };

  event.waitUntil(
    self.registration.showNotification(data.title || 'Smart Daily Planner', options)
  );
});

// Listen for notification click events
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const urlToOpen = event.notification.data?.url || '/notifications';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // If a window is already open, focus it and redirect
      for (let client of windowClients) {
        const clientUrl = new URL(client.url);
        if (clientUrl.origin === self.location.origin) {
          if ('focus' in client) {
            client.navigate(urlToOpen);
            return client.focus();
          }
        }
      }
      // If no window is open, open a new tab
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
